chore: remove warnings and fix compilation issue
If nomt is included within a crate that also includes the `bytes` crate,
it produces a compilation error:
`the trait `PartialOrd<&Vec<u8>>` is not implemented for `Vec<u8>``
which is solved by dereferencing the `&Vec<u8>`.

This is an open bug within rustc: https://github.com/rust-lang/rust/issues/130464